# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_SZpack', [dirname(__file__)])
        except ImportError:
            import _SZpack
            return _SZpack
        if fp is not None:
            try:
                _mod = imp.load_module('_SZpack', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _SZpack = swig_import_helper()
    del swig_import_helper
else:
    import _SZpack
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr



def compute_5d(*args):
    return _SZpack.compute_5d(*args)
compute_5d = _SZpack.compute_5d

def compute_3d(*args):
    return _SZpack.compute_3d(*args)
compute_3d = _SZpack.compute_3d

def compute_asym(*args):
    return _SZpack.compute_asym(*args)
compute_asym = _SZpack.compute_asym

def compute_CNSN(*args):
    return _SZpack.compute_CNSN(*args)
compute_CNSN = _SZpack.compute_CNSN

def compute_CNSN_opt(*args):
    return _SZpack.compute_CNSN_opt(*args)
compute_CNSN_opt = _SZpack.compute_CNSN_opt

def compute_combo(*args):
    return _SZpack.compute_combo(*args)
compute_combo = _SZpack.compute_combo

def compute_combo_means(*args):
    return _SZpack.compute_combo_means(*args)
compute_combo_means = _SZpack.compute_combo_means

def compute_combo_means_ex(*args):
    return _SZpack.compute_combo_means_ex(*args)
compute_combo_means_ex = _SZpack.compute_combo_means_ex

def compute_null(tau, TeSZ, betac_para, omega1, sigma, kappa, betac2_perp):
    return _SZpack.compute_null(tau, TeSZ, betac_para, omega1, sigma, kappa, betac2_perp)
compute_null = _SZpack.compute_null


